import "@/assets/styles/globals.css";

import type { Metadata } from "next";

import PublicHeader from "@/components/global/PublicHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="overflow-x-hidden">
      <PublicHeader />
      {children}
    </div>
  );
}
