services:
  postgres:
    image: postgres:latest
    container_name: signaliconisp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signalicon # This creates the database named 'signalicon'
    ports:
      - "5432:5432"
    networks:
      - signalicon-network

  redis:
    image: redis:latest
    container_name: signaliconisp-redis
    environment:
      REDIS_PASSWORD: redis # Set the password for Redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis"] # Require password for Redis
    networks:
      - signalicon-network

networks:
  signalicon-network:
