services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${EMAIL_SERVER_PORT}:1025
      - ${EMAIL_SERVER_HTTP_PORT}:8025
    volumes:
      - ../../docker-data/mailhog:/maildir